const express = require('express');

//to reactivate import mode, adjust package.json to include under main node:
//"type": "module", 

//const fetch = require('node-fetch');
//var Request = require("request");

//const axios = require('axios');
const sharp = require('sharp');

const PORT = process.env.PORT || 80
const version = 0.1

const fs = require("fs"); // Or `import fs from "fs";` with ESM
const path = require('path');
const S3 = require('aws-sdk').S3;


//const fs = require("fs");

var app = express()
var config = null

//const https = require('https');

//adding multer implementation to handle image uploads
const multer = require('multer');

const cors = require('cors');

app.use(cors());


//load configuration file
loadConfig();




const awsLink = config.AWS_LINK; 
const imagesDir = config.IMG_DIR;

const extraStoragePath = config.EXTRA_STRG;

// Multer configuration for storing uploaded images
const storage = multer.diskStorage({ 
	destination: function (req, file, cb) { 
		cb(null, path.join(__dirname, imagesDir)); 
	}, 
	filename: function (req, file, cb) { 
		cb(null, file.originalname); 
	} 
});

const fileFilter = (req, file, cb) => { 
	// Accept images only 
	console.log(file.mimetype);
	/*if (!file.mimetype.startsWith('image/')) { 
		return cb(new Error('Only image files are allowed!'), false); 
	} */
	cb(null, true); 
};

const upload = multer({ 
	storage: storage,
	fileFilter: fileFilter	
});




function loadConfig() {
	config = JSON.parse(fs.readFileSync("config.json"));
}



const secretKey = config.SEC_UPL_KEE;
const secondSecretKey = config.SEC_UPL_KEE_LEG;

//object storage (Hetzner, S3-compatible) acts as the third storage tier, behind
//the local disk and the mounted volume. Stays disabled unless fully configured,
//so the app keeps working exactly as before if the config is absent.
const objectStorageEnabled = Boolean(
	config.OBJ_ENDPOINT && config.OBJ_BUCKET && config.OBJ_KEY && config.OBJ_SECRET
);

let s3 = null;
if (objectStorageEnabled) {
	s3 = new S3({
		endpoint: config.OBJ_ENDPOINT,
		accessKeyId: config.OBJ_KEY,
		secretAccessKey: config.OBJ_SECRET,
		region: config.OBJ_REGION || 'hel1',
		s3ForcePathStyle: true,
		signatureVersion: 'v4'
	});
	console.log('object storage enabled: bucket ' + config.OBJ_BUCKET + ' at ' + config.OBJ_ENDPOINT);
} else {
	console.log('object storage disabled (OBJ_* config missing); serving from disk only');
}

//images are immutable once written - the filename is a UUID generated by the
//client - so they can be cached indefinitely.
const CACHE_CONTROL = 'public, max-age=31536000, immutable';

const CONTENT_TYPES = {
	'.jpg': 'image/jpeg',
	'.jpeg': 'image/jpeg',
	'.png': 'image/png',
	'.gif': 'image/gif',
	'.webp': 'image/webp'
};

function contentTypeFor(fileName) {
	return CONTENT_TYPES[path.extname(fileName).toLowerCase()] || 'image/jpeg';
}

//the image name lands directly in filesystem paths, so anything that could climb
//out of the images directory has to be rejected. Express decodes %2F into a real
//slash after route matching, so "..%2F..%2Fetc%2Fpasswd" would otherwise reach
//fs/sendFile as a traversal.
function safeImageName(requested) {
	if (typeof requested !== 'string' || requested.length === 0 || requested.length > 255) {
		return null;
	}
	if (requested !== path.basename(requested)) {
		return null;
	}
	if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(requested)) {
		return null;
	}
	return requested;
}

//copy a file that is already on local disk into the bucket. Never throws: a
//storage outage must not fail an upload that has already been written to disk.
async function pushToBucket(filePath, key) {
	if (!s3) {
		return false;
	}
	try {
		await s3.putObject({
			Bucket: config.OBJ_BUCKET,
			Key: key,
			Body: fs.createReadStream(filePath),
			ContentType: contentTypeFor(key),
			CacheControl: CACHE_CONTROL
		}).promise();
		console.log('pushed to bucket: ' + key);
		return true;
	} catch (err) {
		console.error('failed pushing ' + key + ' to bucket:', err.message);
		return false;
	}
}

async function fetchMeta(imgParam){
	let input = 'loadedimgs/'+imgParam;
	const metadata = await sharp(input).metadata();
	console.log(metadata);
	let inst = sharp('loadedimgs/'+imgParam).rotate().toFile('loadedimgs/'+imgParam+'_fixed');
	return;
}


function verifySecretKey(req, res, next) {
  const token = req.headers['authorization'];

  if (token !== secretKey && token !== secondSecretKey) {
    return res.status(403).send('Unauthorized access. Invalid token.');
  }

  next();
}

// Helper: Universally handles image orientation for all formats.
async function fixOrientationAndStripExif(filePath) {
  try {
    // 1. Read the original file into a buffer. This works for any format.
    const originalBuffer = await fs.promises.readFile(filePath);

    // 2. Get the image's true metadata from the buffer.
    const metadata = await sharp(originalBuffer).metadata();

    // 3. Check if an orientation tag exists and requires rotation.
    //    (This tag is typically only found in JPEG and TIFF files).
    if (!metadata.orientation || metadata.orientation === 1) {
      // If orientation is normal or doesn't exist (e.g., for a PNG), do nothing.
      console.log(`Image ${filePath} (format: ${metadata.format}) does not require rotation. File left untouched.`);
      return {
        rotated: false,
        metadataBefore: metadata
      };
    }

    // 4. If we get here, rotation IS required. Calculate the angle.
    let rotationAngle = 0;
    switch (metadata.orientation) {
      case 3: rotationAngle = 180; break;
      case 6: rotationAngle = 90; break;
      case 8: rotationAngle = 270; break;
    }
    
    console.log(`Image ${filePath} (format: ${metadata.format}) has orientation tag ${metadata.orientation}. Applying ${rotationAngle}-degree rotation.`);

    // 5. Create a new buffer with the physically rotated image.
    //    Sharp will automatically preserve the original format (JPEG, etc.).
    const rotatedBuffer = await sharp(originalBuffer)
      .rotate(rotationAngle)
      .toBuffer();

    // 6. Overwrite the original file with the new, corrected buffer.
    await fs.promises.writeFile(filePath, rotatedBuffer);

    console.log(`Successfully rotated and saved ${filePath}.`);

    return {
      rotated: true,
      metadataBefore: metadata
    };

  } catch (err) {
    console.error(`CRITICAL: An error occurred during orientation check for ${filePath}.`, err);
    throw err;
  }
}


app.get('/', async function (req,res){
	res.send('EHLO');
})

app.post('/upload', verifySecretKey, upload.single('image'), async function (req, res) { 
	try { 
    if (!req.file) {
      return res.status(400).send('No file uploaded.');
    }

    const savedPath = req.file.path; // full path where multer saved the file
    console.log('Uploaded file info:', req.file);

    try {
      const result = await fixOrientationAndStripExif(savedPath);
      console.log('fixOrientationAndStripExif result:', result);

      //mirror to object storage after the orientation fix, so the bucket holds
      //the corrected image rather than the raw upload. The local copy is still
      //written and served first, so a bucket failure only costs us the mirror.
      const mirrored = await pushToBucket(savedPath, req.file.filename);

      // Send response back to client
      return res.status(200).json({
        message: 'Image uploaded and processed successfully!',
        rotated: result.rotated,
        mirrored: mirrored,
        originalMetadata: {
          format: result.metadataBefore.format,
          size: result.metadataBefore.size,
          orientation: result.metadataBefore.orientation || 1
        }
      });
    } catch (processingErr) {
      console.error('Error processing image:', processingErr);
      // Optionally return success for upload but warn about processing error:
      return res.status(500).json({ message: 'Image uploaded but failed to process orientation/EXIF.', error: processingErr.message });
    }

  } catch (err) { 
    console.error('Upload error:', err);
    res.status(500).send('An error occurred while uploading the image.');
  }
});

app.get('/fetchMeta/:imgParam', async function (req, res){
	let outc = await fetchMeta(req.params.imgParam);
	res.send('done');
})


//Disabled. This route walked every local image and called deleteFileAWS(), which
//has been commented out for years - so any request threw a ReferenceError inside
//an async handler. Express does not catch those, the rejection went unhandled,
//and on current Node that terminates the process. It was also unauthenticated,
//unlike /upload, so it was reachable by anyone. Kept as an explicit 410 rather
//than removed outright, in case something still calls it.
app.get('/deleteOrigin', function (req, res){
	return res.status(410).send({error: 'deleteOrigin is no longer available'});
})

/*
async function deleteFileAWS(fileName){
	console.log('deleting '+fileName);
	let aws_params = {
		Bucket: "actifit", 
		Key: fileName
	};
	let outc = await s3.deleteObject(aws_params).promise();
	//console.log(outc);
	console.log('done');
}*/

app.get('/:imgParam', async function (req, res){
	const imgName = safeImageName(req.params.imgParam);
	if (!imgName) {
		console.log('rejected image name: ' + req.params.imgParam);
		return res.send({error:'no match'});
	}

	//content type is set explicitly rather than left to sendFile: some stored
	//images have no extension, and sendFile would label those
	//application/octet-stream, which makes browsers download instead of render.
	const contentType = contentTypeFor(imgName);

	//tier 1: local disk
	const localPath = __dirname + imagesDir + imgName;
	if (fs.existsSync(localPath)) {
		res.set('Cache-Control', CACHE_CONTROL);
		res.type(contentType);
		return res.sendFile(localPath);
	}

	//tier 2: mounted volume
	const volumePath = extraStoragePath + imagesDir + imgName;
	if (fs.existsSync(volumePath)) {
		res.set('Cache-Control', CACHE_CONTROL);
		res.type(contentType);
		return res.sendFile(volumePath);
	}

	//tier 3: object storage. Server-to-bucket traffic stays inside the Hetzner
	//network zone, so it is free and only costs one internal round trip.
	if (s3) {
		try {
			const obj = await s3.getObject({
				Bucket: config.OBJ_BUCKET,
				Key: imgName
			}).promise();
			res.set('Cache-Control', CACHE_CONTROL);
			res.type(contentType);
			return res.send(obj.Body);
		} catch (err) {
			if (err.code !== 'NoSuchKey' && err.statusCode !== 404) {
				console.error('bucket fetch failed for ' + imgName + ':', err.message);
			}
		}
	}

	console.log('no match for ' + imgName);
	return res.send({error:'no match'});
})


app.listen(PORT);
console.log('Server started on port '+PORT);
